Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/AbcSize:
  Max: 20

Style/ClassVars:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Lint/Void:
  Enabled: false
